### ISSUE TITLE
Issues with CHOpt 1.9.0

### ISSUE THREAD

**Issue by tposejank** [GenericMadScientist/CHOpt#15]
The latest CHOpt update which added support for FNF Pro instruments has come with some small bugs, I'd like to list them all here

1. The CLI binary requires the Qt DLLs to be present in the directory, I don't know if that's intentional 
2. An unknown error occurs and CHOpt does not return the path

For 1: When the Festival Tracker Discord bot updated to the newest version, a binary had been built from GitHub Actions in jnack's fork, because the .exe required DLLs and he didn't know that

For 2: Error is unknown but it is present:
![Screenshot_20241007_124411_Discord](https://github.com/user-attachments/assets/e4585155-27d0-4a56-8867-fc6beb8da082)
The bot sometimes fails to read the console output, however I was unable to reproduce the issue on my own

**Comment by GenericMadScientist** [comment]
On 1, that's because I moved to using Qt for the CLI version as well. Completely intentional.

2 is more serious. I encountered it myself yesterday while trying to update gmscorner.dev to CHOpt 1.9.1, although it wouldn't surprise me that the issue is present in 1.9.0 as well. Probably caused by a bug introduced while switching to Qt to handle the command line arguments. Once I have time this is _the_ top priority to fix (enough that CHOpt 1.9.2 will just be this bug fix), and thankfully I do have a local reproduction.

**Comment by GenericMadScientist** [comment]
Dug into my local reproduction and I found the bug, added in 1.9.1 but jnack's fork is after the responsible change. The fix is out in 1.9.2. If you still have any problems I'd be very interested to find out so please do open another issue if that's the case.

**Comment by tposejank** [comment]
Thanks! jnack will update it tomorrow, then it will be possible to see if there are any issues.
