### ISSUE TITLE
CHOpt doesn't see starpower phrase?

### ISSUE THREAD

**Issue by Xane8** [GenericMadScientist/CHOpt#4]
![Screenshot 2022-10-16 124646](https://user-images.githubusercontent.com/115923642/196031060-a35e75b8-2788-4cd5-842c-c021bc6a2d66.png)

This one specific phrase in triathlon isn't seen by the program. It doesn't overlap or give you starpower after is this intended or no?

This isn't the first time it happened but i don't remember where was the other instance.

**Comment by GenericMadScientist** [comment]
What settings did you use to generate this? This is definitely a bug, but even with 0%/0% I get far more points by m662 when I generate the path.

**Comment by Xane8** [comment]
weird, i used default settings, maybe that's the problem
CHOpt.exe -f notes.chart -d expert -o triathlon_path.png

default settings
![image](https://user-images.githubusercontent.com/115923642/196037128-b2c2a045-f130-40eb-aa7a-9fbc44e34c52.png)
0%/0%
![image](https://user-images.githubusercontent.com/115923642/196037143-65122f74-e793-474a-bb80-ade439b3c410.png)

**Comment by GenericMadScientist** [comment]
Okay, I better see what is going on now. The 100%/100% path is correct, and the SP is getting picked up in the calculations because otherwise it would be impossible to activate in m664. It's just that the SP percentage calculation is incorrect (and this is done separately). I'll look into fixing it, but at any rate you can trust the path itself.

The paths are different for 0% and 100% because of reverse squeezing: you need to be able to overlap the entire m660 phrase while not overlapping the m662 phrase, and there are less than two measures between the last notes of each so this requires good squeezing.

As for having less points than when I run it, it turns out that's just because my version of the chart has solo markers while yours does not.

**Comment by GenericMadScientist** [comment]
Sorry for taking so long to get round to this. Fixed in 1.6.0.
